### ISSUE TITLE
clientPort is deprecated

### ISSUE THREAD

**Issue by calestyo** [phunt/zktop#29]
Hey.

AFAIU, `clientPort` is deprecated,... but when one removes it, zktop fails:
```
Traceback (most recent call last):
  File "/usr/bin/zktop", line 11, in <module>
    load_entry_point('zktop==1.0.0', 'console_scripts', 'zktop')()
  File "/usr/lib/python3/dist-packages/zktop.py", line 392, in main_func
    ui = Main(get_zk_servers(options.configfile))
  File "/usr/lib/python3/dist-packages/zktop.py", line 385, in get_zk_servers
    client_port = config['clientPort']
KeyError: 'clientPort'
```

Cheers,
Chris.

**Comment by phunt** [comment]
Where does it say deprecated? I see it in the docs still here:
https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html
There is a new secureClientPort - zktop only works with plaintext today afaik.

**Comment by calestyo** [comment]
Hey.

I had read that here:
https://zookeeper.apache.org/doc/r3.5.3-beta/zookeeperReconfig.html

> Starting with 3.5.0 the clientPort and clientPortAddress configuration parameters should no longer be used. Instead, this information is now part of the server keyword specification, which becomes as follows:
> ```server.<positive id> = <address1>:<port1>:<port2>[:role];[<client port address>:]<client port> ```

And interestingly, the software that I use, which makes use of ZK,... that is [dCache](http://dcache.org/), gives warnings, when I use `clientPort` instead of the other way.... it must be able to somehow detect this via ZK itself and not by reading it's config files.

**Comment by phunt** [comment]
Yea, I vaguely remember something about reconfig needing that, in order to support reconfig of those params or something.... tbh it looks like it didn't make it in fully. I didn't find any JIRA when I looked, although it's not easy to search for.

**Comment by calestyo** [comment]
Hmm, yes it feels a bit like that, cause as you've said... it's not really mentioned in the docs anymore.

Still, it would be nice if zktop could support both, cause as I've said, the software which I use that uses ZK, gives strange errors when one still uses `clientPort`.
